### ISSUE TITLE
Getting javascript error when Metrics tab is opened

### ISSUE THREAD

**Issue by awwwd** [argoproj-labs/argocd-extension-metrics#41]
Getting "Something went wrong with Extension for Pod" when Matrics tab is opened

Also in the javascript console seeing some errors:
```
main.6d68d77ebcfffd06ce4d.js:2 TypeError: an is not a function
    at tickFormatter (extensions.js:2:525802)
    at R.s.ticks (extensions.js:2:157187)
    at R (extensions.js:2:157543)
    at i.value (extensions.js:2:166796)
    at i.value (extensions.js:2:167989)
    at Hs (main.6d68d77ebcfffd06ce4d.js:2:820265)
    at js (main.6d68d77ebcfffd06ce4d.js:2:820060)
    at ya (main.6d68d77ebcfffd06ce4d.js:2:855541)
    at pl (main.6d68d77ebcfffd06ce4d.js:2:847016)
    at ul (main.6d68d77ebcfffd06ce4d.js:2:846941)
na @ main.6d68d77ebcfffd06ce4d.js:2
main.6d68d77ebcfffd06ce4d.js:2 TypeError: an is not a function
    at tickFormatter (extensions.js:2:525802)
    at R.s.ticks (extensions.js:2:157187)
    at R (extensions.js:2:157543)
    at extensions.js:2:205261
    at l.value (extensions.js:2:116428)
    at Hs (main.6d68d77ebcfffd06ce4d.js:2:820265)
    at js (main.6d68d77ebcfffd06ce4d.js:2:820060)
    at ya (main.6d68d77ebcfffd06ce4d.js:2:855541)
    at pl (main.6d68d77ebcfffd06ce4d.js:2:847016)
    at ul (main.6d68d77ebcfffd06ce4d.js:2:846941)
```

Metrics Extension API calls seems to be fine -
<img width="1792" alt="image" src="https://github.com/argoproj-labs/argocd-extension-metrics/assets/11169900/604e8e73-64ad-4de2-b7ab-4c978dea9ea5">
 
argo: v2.7.2
argocd-extension-metrics: v0.0.3-rc2
argocd-extensions: latest

**Comment by sarabala1979** [comment]
@dsmithco 
can you take a look?
